import { describe, expect, it } from 'vitest';
import {
  buildDebugSnapshotExport,
  formatDebugSnapshotFilename,
} from './debug-snapshot.ts';

describe('debug snapshot', () => {
  it('builds a structured export from the current debug snapshot and history', () => {
    const timestamp = new Date('2026-08-08T15:11:20.000Z');
    const result = buildDebugSnapshotExport({
      timestamp,
      gameVersion: '0.1.0',
      buildId: 'abc1234',
      worldSeed: 'alpha',
      context: {
        id: 'town:3:7',
        type: 'town',
        label: 'Town',
        depth: 1,
      },
      player: {
        gridX: 14,
        gridY: -9,
        worldX: 14.25,
        worldY: -8.6,
        facing: 90,
      },
      rendererMode: '3d',
      activeContentPacks: [{ id: 'default-content-pack', name: 'Default Pack' }],
      enabledPlugins: ['tile-forest', 'map-town'],
      graphicsQuality: {
        level: 'Reduced',
        limiters: 'Target FPS reduced to 30',
        renderRadius: 14,
        targetFps: 30,
        performanceTier: 'reduced',
      },
      device: {
        userAgent: 'TestBrowser/1.0',
        language: 'en-US',
        platform: 'MacIntel',
        hardwareConcurrency: 8,
        deviceMemoryGb: 16,
      },
      graphicsCapabilities: {
        webgpuSupported: false,
        webgl2Supported: true,
        webglSupported: true,
        renderer: 'Fake GPU',
        vendor: 'Fake Vendor',
        maxTextureSize: 8192,
        maxCubeMapTextureSize: 4096,
        maxRenderbufferSize: 2048,
        maxVertexUniformVectors: 1024,
        maxFragmentUniformVectors: 512,
        maxCombinedTextureImageUnits: 32,
        antialias: true,
      },
      performanceBudget: {
        currentFrameMs: 22.4,
        smoothedFrameMs: 24.1,
        targetFps: 30,
        visibilityRadius: 14,
        pendingBuildBudgetMs: 2.25,
        maxPendingBuildTiles: 4,
        caps: {
          frameMs: {
            soft: 1000 / 42,
            hard: 1000 / 28,
          },
          visibilityRadius: {
            full: 18,
            reduced: 14,
            minimum: 10,
          },
          pendingBuildBudgetMs: {
            minimum: 0.75,
            maximum: 2.25,
          },
          pendingBuildTiles: {
            soft: 4,
            hard: 2,
          },
        },
      },
      lod: {
        thresholds: {
          lowDetailDistance: 6.5,
          lowDetailEnterDistance: 6.5,
          lowDetailExitDistance: 6,
          hysteresisDistance: 0.5,
          pendingBuildFullDetailDistance: 3,
          syncMovementDistance: 0.18,
        },
      },
      snapshot: {
        fps: 44.6,
        averageFps: 46.2,
        frameMs: 22.4,
        worstRecentFrameMs: 31.8,
        targetFps: 30,
        performanceTier: 'reduced',
        renderQualityLevel: 'Reduced',
        renderQualityLimiters: 'Target FPS reduced to 30',
        playerLevel: 5,
        visibilityRadius: 14,
        drawCalls: 420,
        triangles: 120000,
        points: 90,
        lines: 12,
        renderWidth: 1536,
        renderHeight: 864,
        devicePixelRatio: 2,
        renderScale: 1,
        sceneChildCount: 8,
        visibleTileCount: 112,
        visibleTreeCount: 24,
        loadedChunkCount: 112,
        chunkGenerationQueueSize: 6,
        pendingTileCount: 6,
        averagePendingFlushTiles: 3,
        maxPendingFlushTiles: 5,
        averageTileBuildMs: 2.4,
        maxTileBuildMs: 6.8,
        tileNodeBuildsPerSecond: 14,
        tileBuildsPerSecond: 11,
        lodChecksPerSecond: 5,
        lodReplacementsPerSecond: 3,
        object3dCount: 318,
        visibleObjectCount: 301,
        invisibleObjectCount: 17,
        groupCount: 54,
        meshCount: 180,
        instancedMeshCount: 6,
        visibleInstancedMeshCount: 5,
        renderedInstanceCount: 248,
        visibleMeshCount: 164,
        maxHierarchyDepth: 7,
        averageHierarchyDepth: 2.6,
        emptyGroupCount: 12,
        oneChildGroupCount: 18,
        matrixAutoUpdateCount: 22,
        staticMatrixAutoUpdateCount: 15,
        pointsCount: 5,
        lineObjectCount: 7,
        activeParticleSystemCount: 4,
        activeParticleCount: 90,
        spriteCount: 9,
        cameraCount: 1,
        lightCount: 12,
        dynamicLightCount: 4,
        shadowLightCount: 2,
        activeNpcCount: 19,
        fullSimulationEntityCount: 21,
        reducedSimulationEntityCount: 2,
        activeAudioSourceCount: 6,
        materialRefCount: 38,
        materialCount: 24,
        sharedMaterialCount: 14,
        clonedMaterialCount: 3,
        transparentMaterialCount: 6,
        alphaTestMaterialCount: 4,
        doubleSidedMaterialCount: 9,
        fogMaterialCount: 19,
        customShaderMaterialCount: 2,
        materialTypes: 'MeshBasicMaterial:4, MeshStandardMaterial:14, ShaderMaterial:2, SpriteMaterial:4',
        materialsCreatedDuringSamplingWindow: 5,
        materialsDisposedDuringSamplingWindow: 2,
        geometryCount: 61,
        vertexCount: 14432,
        geometryMemoryCount: 63,
        treeObjectCount: 216,
        treeMeshCount: 135,
        treeMaterialRefCount: 135,
        visibleTileKindSummary: 'forest:48, plains:32',
        textureCount: 7,
        textureMemoryEstimateMb: 12.5,
        programCount: 12,
        latitude: 32.1234,
        longitude: -81.5678,
        gridX: 14,
        gridY: -9,
        worldSeed: 'alpha',
        heapUsedMb: 48.4,
        heapLimitMb: 128,
        resourceWarnings: [],
      },
      history: [
        {
          nowMs: 0,
          fps: 58.5,
          frameMs: 17.1,
          drawCalls: 398,
          triangles: 116000,
          objectCount: 304,
          materialCount: 23,
          geometryCount: 59,
          heapUsedMb: 47.2,
          tileBuildsPerSecond: 13,
          lodReplacementsPerSecond: 1,
          visibleTileCount: 109,
          visibleTreeCount: 26,
          activeLightCount: 10,
          activeParticleSystemCount: 2,
          activeParticleCount: 48,
          generationQueueSize: 3,
        },
        {
          nowMs: 1000,
          fps: 48,
          frameMs: 20.8,
          drawCalls: 405,
          triangles: 118000,
          objectCount: 310,
          materialCount: 24,
          geometryCount: 60,
          heapUsedMb: 47.9,
          tileBuildsPerSecond: 12,
          lodReplacementsPerSecond: 2,
          visibleTileCount: 110,
          visibleTreeCount: 25,
          activeLightCount: 11,
          activeParticleSystemCount: 3,
          activeParticleCount: 72,
          generationQueueSize: 4,
        },
        {
          nowMs: 2000,
          fps: 44.6,
          frameMs: 22.4,
          drawCalls: 420,
          triangles: 120000,
          objectCount: 318,
          materialCount: 24,
          geometryCount: 61,
          heapUsedMb: 48.4,
          tileBuildsPerSecond: 11,
          lodReplacementsPerSecond: 3,
          visibleTileCount: 112,
          visibleTreeCount: 24,
          activeLightCount: 12,
          activeParticleSystemCount: 4,
          activeParticleCount: 96,
          generationQueueSize: 6,
        },
      ],
    });

    expect(result.metadata.timestamp).toBe('2026-08-08T15:11:20.000Z');
    expect(result.metadata.gameVersion).toBe('0.1.0');
    expect(result.metadata.buildId).toBe('abc1234');
    expect(result.metadata.context.id).toBe('town:3:7');
    expect(result.metadata.activeContentPacks[0]?.id).toBe('default-content-pack');
    expect(result.metadata.enabledPlugins).toEqual(['tile-forest', 'map-town']);
    expect(result.metadata.graphicsCapabilities).toMatchObject({
      webgpuSupported: false,
      webgl2Supported: true,
      webglSupported: true,
      renderer: 'Fake GPU',
      vendor: 'Fake Vendor',
      maxTextureSize: 8192,
      maxCombinedTextureImageUnits: 32,
      antialias: true,
    });
    expect(result.metadata.performanceBudget).toMatchObject({
      currentFrameMs: 22.4,
      targetFps: 30,
      visibilityRadius: 14,
      pendingBuildBudgetMs: 2.25,
      maxPendingBuildTiles: 4,
      caps: {
        frameMs: {
          soft: 1000 / 42,
          hard: 1000 / 28,
        },
        pendingBuildBudgetMs: {
          minimum: 0.75,
          maximum: 2.25,
        },
        pendingBuildTiles: {
          soft: 4,
          hard: 2,
        },
      },
    });
    expect(result.summary).toMatchObject({
      currentFps: 44.6,
      averageFps: 46.2,
      minimumFps: 44.6,
      averageFrameMs: 20.1,
      p50FrameMs: 20.8,
      p95FrameMs: 22.4,
      p99FrameMs: 22.4,
      targetFrameMs: 1000 / 30,
      performanceTier: 'reduced',
      framesOver16_7Ms: 3,
      framesOver33_3Ms: 0,
      framesOver50Ms: 0,
      cpuFrameMs: 22.4,
    });
    expect(result.rendering).toMatchObject({
      drawCalls: 420,
      triangles: 120000,
      vertices: 14432,
      renderWidth: 1536,
      renderHeight: 864,
      devicePixelRatio: 2,
      renderScale: 1,
      visibleInstancedMeshCount: 5,
      renderedInstanceCount: 248,
      visibleMeshCount: 164,
    });
    expect(result.sceneGraph).toMatchObject({
      object3dCount: 318,
      visibleObjectCount: 301,
      invisibleObjectCount: 17,
      groupCount: 54,
      meshCount: 180,
      instancedMeshCount: 6,
      renderedInstanceCount: 248,
      maxHierarchyDepth: 7,
      averageHierarchyDepth: 2.6,
      emptyGroupCount: 12,
      oneChildGroupCount: 18,
      matrixAutoUpdateCount: 22,
      staticMatrixAutoUpdateCount: 15,
      pointsCount: 5,
      lineObjectCount: 7,
      cameraCount: 1,
      lightCount: 12,
    });
    expect(result.resources).toMatchObject({
      totalMaterialReferences: 38,
      uniqueMaterialCount: 24,
      sharedMaterialCount: 14,
      clonedMaterialCount: 3,
      transparentMaterialCount: 6,
      alphaTestMaterialCount: 4,
      doubleSidedMaterialCount: 9,
      fogMaterialCount: 19,
      customShaderMaterialCount: 2,
      materialTypes:
        'MeshBasicMaterial:4, MeshStandardMaterial:14, ShaderMaterial:2, SpriteMaterial:4',
      materialsCreatedDuringSamplingWindow: 5,
      materialsDisposedDuringSamplingWindow: 2,
      geometryCount: 61,
      textureCount: 7,
      textureMemoryEstimateMb: 12.5,
      geometryMemoryCount: 63,
    });
    expect(result.particles).toMatchObject({
      activeParticleSystems: 4,
      activeParticles: 90,
      maxParticlesDuringSamplingWindow: 96,
    });
    expect(result.shaderPrograms).toMatchObject({
      currentProgramCount: 12,
    });
    expect(result.lighting).toMatchObject({
      currentlyActiveLights: 12,
      shadowCastingLights: 2,
    });
    expect(result.world).toMatchObject({
      currentMapId: 'town:3:7',
      currentMapType: 'town',
      currentMapDepth: 1,
      visibleTileCount: 112,
      loadedTileCount: 112,
      pendingTileBuildCount: 6,
      tileBuildsPerSecond: 11,
      averageTileBuildMs: 2.4,
      worstTileBuildMs: 6.8,
      tileKinds: 'forest:48, plains:32',
    });
    expect(result.lod).toMatchObject({
      checksPerSecond: 5,
      swapsPerSecond: 3,
      thresholds: {
        lowDetailDistance: 6.5,
        lowDetailEnterDistance: 6.5,
        lowDetailExitDistance: 6,
        hysteresisDistance: 0.5,
        pendingBuildFullDetailDistance: 3,
        syncMovementDistance: 0.18,
      },
    });
    expect(result.resources).toMatchObject({
      uniqueMaterialCount: 24,
      geometryCount: 61,
      textureCount: 7,
      textureMemoryEstimateMb: 12.5,
      geometryMemoryCount: 63,
    });
    expect(result.textures).toMatchObject({
      textureCount: 7,
      decodedTextureMemoryEstimateMb: 12.5,
    });
    expect(result.history).toEqual([
      expect.objectContaining({
        t: -2,
        fps: 58.5,
        activeParticleSystemCount: 2,
        activeParticleCount: 48,
        generationQueueSize: 3,
      }),
      expect.objectContaining({
        t: -1,
        fps: 48,
        activeParticleSystemCount: 3,
        activeParticleCount: 72,
        generationQueueSize: 4,
      }),
      expect.objectContaining({
        t: 0,
        fps: 44.6,
        activeParticleSystemCount: 4,
        activeParticleCount: 96,
        generationQueueSize: 6,
      }),
    ]);
  });

  it('formats debug snapshot filenames with a stable timestamp pattern', () => {
    expect(
      formatDebugSnapshotFilename(new Date('2026-08-08T15:11:20.000Z'))
    ).toBe('bworlds-debug-20260808-151120.json');
  });
});
