export const CHUNK_SIZE = 32;
export const EARTH_CIRCUMFERENCE_METERS = 40075017;
export const TILE_METERS = 250;
export const WORLD_TILES_WIDE = Math.floor(
  EARTH_CIRCUMFERENCE_METERS / TILE_METERS
);
export const HALF_WORLD_TILES = WORLD_TILES_WIDE / 2;
export const DEFAULT_DAY_LENGTH_MINUTES = 42;
export const DEFAULT_DAY_LENGTH_MS = DEFAULT_DAY_LENGTH_MINUTES * 60 * 1000;
export const DEFAULT_YEAR_LENGTH_DAYS = 64;
export const DEFAULT_CONSTELLATION_COUNT = 8;
export const DEFAULT_SEASON_DAYLIGHT_AMPLITUDE = 0.41;
